# Generated by Django 4.1.3 on 2022-11-06 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entregable',
            name='fechaDeEntrega',
            field=models.DateField(default=datetime.datetime(2022, 11, 6, 19, 21, 14, 923451), verbose_name='Date'),
        ),
    ]
