# Generated by Django 4.1.3 on 2022-11-06 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0002_entregable_entregado_entregable_fechadeentrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fechaDeNacimiento', models.DateField(default=datetime.datetime(2022, 11, 6, 19, 27, 39, 96081), verbose_name='Date')),
                ('ciudad', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='entregable',
            name='fechaDeEntrega',
            field=models.DateField(default=datetime.datetime(2022, 11, 6, 19, 27, 39, 96081), verbose_name='Date'),
        ),
    ]
