# Generated by Django 4.1.3 on 2022-11-16 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0003_familiares_alter_entregable_fechadeentrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='fechaDeEntrega',
            field=models.DateField(default=datetime.datetime(2022, 11, 16, 1, 4, 22, 61783), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='familiares',
            name='fechaDeNacimiento',
            field=models.DateField(default=datetime.datetime(2022, 11, 16, 1, 4, 22, 61783), verbose_name='Date'),
        ),
    ]
